const ITEMS = {
    "fakard_01": { 
        id: "fakard_01", 
        name: "Ócska Fakard", 
        type: "fegyver",
        price: 150,
        sellPrice: 35,
        atk: 2, 
        def: 0, 
        rarity: "common", 
        img: "https://i.ibb.co/twxWwxFJ/Copilot-20260405-035308.png" 
    },
    "rezkard_01": { 
        id: "rezkard_01", 
        name: "Réz Kard", 
        type: "fegyver",
        price: 450,
        sellPrice: 120,
        atk: 5, 
        def: 0, 
        rarity: "uncommon", 
        img: "https://i.ibb.co/nNFg9ps5/Copilot-20260405-040140.png" 
    },
    "vaskard_01": { 
        id: "vaskard_01", 
        name: "Harci Vas Kard", 
        type: "fegyver",
        price: 1200,
        sellPrice: 400,
        atk: 12, 
        def: 1, 
        rarity: "rare", 
        img: "https://i.ibb.co/LDcq0LQp/Copilot-20260405-040230.png" 
    },
    "rozsdas_penge_01": {
        id: "rozsdas_penge_01",
        name: "Sírrablók rozsdás pengéje",
        type: "fegyver",
        price: 80,
        sellPrice: 20,
        atk: 1,
        def: 0,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "vaskard_03": {
        id: "vaskard_03",
        name: "Kárhozott fattyúkard",
        type: "fegyver",
        price: 180,
        sellPrice: 50,
        atk: 3,
        def: 0,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "vandor_penge_01": {
        id: "vandor_penge_01",
        name: "Száműzött lovag vándorpenge",
        type: "fegyver",
        price: 650,
        sellPrice: 180,
        atk: 4,
        def: 1,
        rarity: "uncommon",
        effect: "Hárítás: +1 DEF",
        img: ""
    },
    "orulet_tore_02": {
        id: "orulet_tore_02",
        name: "Suttogó árnyak tőre",
        type: "fegyver",
        price: 780,
        sellPrice: 220,
        atk: 5,
        def: 0,
        rarity: "uncommon",
        effect: "Vérzés: +1 sebzés kör végén",
        img: ""
    },
    "lelkek_ore_01": {
        id: "lelkek_ore_01",
        name: "Kárhozott lelkek őrzője",
        type: "fegyver",
        price: 2200,
        sellPrice: 550,
        atk: 5,
        def: 2,
        rarity: "rare",
        effect: "Lélekfaló: +2 HP győzelem után (max 20 stack)",
        img: ""
    },
    "kripta_kard_03": {
        id: "kripta_kard_03",
        name: "Kriptafaló obszidián penge",
        type: "fegyver",
        price: 2400,
        sellPrice: 600,
        atk: 6,
        def: 1,
        rarity: "rare",
        effect: "Kincskereső: +2 arany győzelem után",
        img: ""
    },
    "langnyelv_01": {
        id: "langnyelv_01",
        name: "Alvilági lángnyelv pallos",
        type: "fegyver",
        price: 5500,
        sellPrice: 1400,
        atk: 6,
        def: 1,
        rarity: "epic",
        effect: "Parázs: 10% esély égetésre (2 HP/kör)",
        img: ""
    },
    "vihar_penge_04": {
        id: "vihar_penge_04",
        name: "Viharhozó villámpenge",
        type: "fegyver",
        price: 6000,
        sellPrice: 1500,
        atk: 7,
        def: 0,
        rarity: "epic",
        effect: "Sokk: Kritikusnál +3 villámsebzés",
        img: ""
    },
    "istenveres_01": {
        id: "istenveres_01",
        name: "Égi fémből kovácsolt Istenverés",
        type: "fegyver",
        price: 15000,
        sellPrice: 3800,
        atk: 7,
        def: 2,
        rarity: "legendary",
        effect: "Skill: Sújtás (8 dmg) | Passzív: +5 HP",
        img: ""
    },
    "halal_erintese_03": {
        id: "halal_erintese_03",
        name: "A kaszás éjfekete sarlója",
        type: "fegyver",
        price: 16000,
        sellPrice: 4000,
        atk: 7,
        def: 1,
        rarity: "legendary",
        effect: "Skill: Életaratás (4 HP szívás) | Passzív: +3% Krit",
        img: ""
    },
    "szakadtfelso_01": { 
        id: "szakadtfelso_01", 
        name: "Szakadt Felső", 
        type: "páncél",
        price: 80,
        sellPrice: 20,
        atk: 0, 
        def: 2, 
        rarity: "common", 
        img: "https://i.ibb.co/dsr66j0L/Copilot-20260405-035126.png" 
    },
    "rongyos_kopeny_01": {
        id: "rongyos_kopeny_01",
        name: "Sötét vándor rongyos köpenye",
        type: "pancel",
        price: 60,
        sellPrice: 15,
        atk: 0,
        def: 1,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "bor_melleny_02": {
        id: "bor_melleny_02",
        name: "Korbácsolt bőrheveder",
        type: "pancel",
        price: 110,
        sellPrice: 30,
        atk: 0,
        def: 2,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "tuskes_vert_01": {
        id: "tuskes_vert_01",
        name: "Kínvallatók tüskés bőrvértje",
        type: "pancel",
        price: 600,
        sellPrice: 160,
        atk: 1,
        def: 4,
        rarity: "uncommon",
        effect: "Visszavágás: 1 sebzés támadónak",
        img: ""
    },
    "nehez_lanc_03": {
        id: "nehez_lanc_03",
        name: "Kárhozottak nehéz láncinge",
        type: "pancel",
        price: 900,
        sellPrice: 260,
        atk: 0,
        def: 6,
        rarity: "uncommon",
        effect: "Stabil: +1 DEF",
        img: ""
    },
    "kodos_pancel_02": {
        id: "kodos_pancel_02",
        name: "Vérködbe burkolt nehézvért",
        type: "pancel",
        price: 2100,
        sellPrice: 520,
        atk: 1,
        def: 5,
        rarity: "rare",
        effect: "Vérszívó: 5% esély 1 HP gyógyulásra",
        img: ""
    },
    "fagyos_vert_02": {
        id: "fagyos_vert_02",
        name: "Zúzmarás jéglovag vértje",
        type: "pancel",
        price: 5200,
        sellPrice: 1300,
        atk: 0,
        def: 7,
        rarity: "epic",
        effect: "Deresedés: 5% esély kábításra",
        img: ""
    },
    "arnyek_pancel_03": {
        id: "arnyek_pancel_03",
        name: "Éjfattyak rúnázott páncélja",
        type: "pancel",
        price: 5800,
        sellPrice: 1450,
        atk: 1,
        def: 6,
        rarity: "epic",
        effect: "Árnyékpajzs: Harc elején 4 védőpajzs",
        img: ""
    },
    "sarkany_pikkely_02": {
        id: "sarkany_pikkely_02",
        name: "Őssárkány megkövült pikkelye",
        type: "pancel",
        price: 14500,
        sellPrice: 3600,
        atk: 1,
        def: 7,
        rarity: "legendary",
        effect: "Skill: Sárkánybőr (+3 DEF) | Passzív: DOT védelem",
        img: ""
    },
    "titan_sziv_04": {
        id: "titan_sziv_04",
        name: "Titánok szívéből vert páncél",
        type: "pancel",
        price: 15500,
        sellPrice: 3900,
        atk: 1,
        def: 7,
        rarity: "legendary",
        effect: "Skill: Földrengés (3 dmg) | Passzív: +1 HP reg.",
        img: ""
    },
    "vashalo_01": {
        id: "vashalo_01",
        name: "Kivégzők sötét vashálója",
        type: "helmet",
        price: 100,
        sellPrice: 25,
        atk: 0,
        def: 1,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "koponyas_sisak_02": {
        id: "koponyas_sisak_02",
        name: "Martalócok koponyás sisakja",
        type: "helmet",
        price: 450,
        sellPrice: 120,
        atk: 1,
        def: 2,
        rarity: "uncommon",
        effect: "Rettegés: +1 ATK",
        img: ""
    },
    "ej_latas_sisak_03": {
        id: "ej_latas_sisak_03",
        name: "Éjjeli őrség rúnázott sisakja",
        type: "helmet",
        price: 1800,
        sellPrice: 450,
        atk: 0,
        def: 4,
        rarity: "rare",
        effect: "Fókusz: +5% találati esély",
        img: ""
    },
    "lovagkapocs_04": {
        id: "lovagkapocs_04",
        name: "Kárhozott lovag sötét sisakja",
        type: "helmet",
        price: 4500,
        sellPrice: 1100,
        atk: 1,
        def: 5,
        rarity: "epic",
        effect: "Vérvért: +2 HP minden kör elején",
        img: ""
    },
    "istenarc_05": {
        id: "istenarc_05",
        name: "Ősi istenek márvány sisakja",
        type: "helmet",
        price: 12000,
        sellPrice: 3000,
        atk: 2,
        def: 7,
        rarity: "legendary",
        effect: "Tisztánlátás: Ellenfél védelmének 10%-át áttöri",
        img: ""
    },
    "korhadt_deszka_01": {
        id: "korhadt_deszka_01",
        name: "Sírrablók korhadt pajzsa",
        type: "shield",
        price: 90,
        sellPrice: 20,
        atk: 0,
        def: 2,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "vasszeges_pajzs_02": {
        id: "vasszeges_pajzs_02",
        name: "Lázadók vasszeges pajzsa",
        type: "shield",
        price: 550,
        sellPrice: 140,
        atk: 1,
        def: 3,
        rarity: "uncommon",
        effect: "Tüskék: 1 sebzés a támadónak",
        img: ""
    },
    "erotlen_fal_03": {
        id: "erotlen_fal_03",
        name: "Kripták mozdíthatatlan fala",
        type: "shield",
        price: 2000,
        sellPrice: 500,
        atk: 0,
        def: 5,
        rarity: "rare",
        effect: "Védfal: +5% blokkolási esély",
        img: ""
    },
    "szellempajzs_04": {
        id: "szellempajzs_04",
        name: "Kísértetek áttetsző pajzsa",
        type: "shield",
        price: 5000,
        sellPrice: 1200,
        atk: 0,
        def: 6,
        rarity: "epic",
        effect: "Árnyéktest: 10% esély a sebzés felének elnyelésére",
        img: ""
    },
    "sarkany_pajzs_05": {
        id: "sarkany_pajzs_05",
        name: "Sárkánykirály törhetetlen pajzsa",
        type: "shield",
        price: 14000,
        sellPrice: 3500,
        atk: 1,
        def: 7,
        rarity: "legendary",
        effect: "Sárkánypikkely: Immunitás a kábításra",
        img: ""
    },
    "szakadt_nadrag_01": {
        id: "szakadt_nadrag_01",
        name: "Vándorok szakadt bőrnadrágja",
        type: "leggings",
        price: 70,
        sellPrice: 15,
        atk: 0,
        def: 1,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "lanc_combvert_02": {
        id: "lanc_combvert_02",
        name: "Gyalogosok nehéz láncnadrágja",
        type: "leggings",
        price: 500,
        sellPrice: 130,
        atk: 0,
        def: 3,
        rarity: "uncommon",
        effect: "Merevítés: +1 DEF",
        img: ""
    },
    "acel_labvert_03": {
        id: "acel_labvert_03",
        name: "Sötét acél lábvért",
        type: "leggings",
        price: 2100,
        sellPrice: 520,
        atk: 0,
        def: 5,
        rarity: "rare",
        effect: "Súlyos: Ellenállás a hátralökésnek",
        img: ""
    },
    "titan_combvert_04": {
        id: "titan_combvert_04",
        name: "Titánok ősi lábvértje",
        type: "leggings",
        price: 5200,
        sellPrice: 1300,
        atk: 1,
        def: 6,
        rarity: "epic",
        effect: "Megingathatatlan: -1 bejövő sebzés minden ütésből",
        img: ""
    },
    "egi_vert_lab_05": {
        id: "egi_vert_lab_05",
        name: "Csillagfényből szőtt lábvért",
        type: "leggings",
        price: 13000,
        sellPrice: 3200,
        atk: 1,
        def: 7,
        rarity: "legendary",
        effect: "Égi léptek: +5 MP körönként",
        img: ""
    },
    "saros_csizma_01": {
        id: "saros_csizma_01",
        name: "Mocsárjárók sáros csizmája",
        type: "boots",
        price: 60,
        sellPrice: 15,
        atk: 0,
        def: 1,
        rarity: "common",
        effect: "Nincs",
        img: ""
    },
    "farkas_bor_02": {
        id: "farkas_bor_02",
        name: "Farkasbőr vadászcsizma",
        type: "boots",
        price: 400,
        sellPrice: 100,
        atk: 1,
        def: 1,
        rarity: "uncommon",
        effect: "Gyorsaság: +3% kitérési esély",
        img: ""
    },
    "arnyek_lepes_03": {
        id: "arnyek_lepes_03",
        name: "Árnyak közt járó csizma",
        type: "boots",
        price: 1800,
        sellPrice: 450,
        atk: 0,
        def: 3,
        rarity: "rare",
        effect: "Néma járás: Első ütésed +3 sebzést ad",
        img: ""
    },
    "szellojaro_04": {
        id: "szellojaro_04",
        name: "Széllovasok rúnázott bakancsa",
        type: "boots",
        price: 4800,
        sellPrice: 1200,
        atk: 0,
        def: 5,
        rarity: "epic",
        effect: "Vihar: +7% kitérési esély",
        img: ""
    },
    "pokoljaro_05": {
        id: "pokoljaro_05",
        name: "Kénköves pokoljáró csizma",
        type: "boots",
        price: 12500,
        sellPrice: 3100,
        atk: 2,
        def: 6,
        rarity: "legendary",
        effect: "Tűzléptek: 2 sebzést okoz az ellenfélnek minden körben",
        img: ""
    },
    "potion_01": {
        id: "potion_01",
        name: "Kisebb Életerő Ital",
        type: "consumable",
        heal: 25,
        price: 50,
        sellPrice: 15,
        rarity: "common",
        img: "https://i.ibb.co/3YChW7rk/Copilot-20260405-034109.png"
    },
    "potion_02": {
        id: "potion_02",
        name: "Nagyobb Életerő Ital",
        type: "consumable",
        heal: 60,
        price: 150,
        sellPrice: 50,
        rarity: "uncommon",
        img: "https://i.ibb.co/fd2Jys7X/Copilot-20260405-035701.png"
    }
};
